    container_name: rails5-web
    build:
      context: containers/nginx
      dockerfile: Dockerfile
      args:
        - USERNAME=$USERNAME
        - UID=$UID
        - NGINX_TAG=$NGINX_TAG
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/$USERNAME/certs/letsencrypt/live/$DOMAIN/fullchain.pem:/etc/nginx/certs/$DOMAIN.crt
      - /home/$USERNAME/certs/letsencrypt/live/$DOMAIN/privkey.pem:/etc/nginx/certs/$DOMAIN.key
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    environment:
      - VIRTUAL_HOST=rails5.$DOMAIN
      - VIRTUAL_PORT=80
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
      - CERT_NAME=$DOMAIN
      - HTTPS_METHOD=noredirect
    expose:
      - "80"
      - "443"
    depends_on:
      - app
    networks:
      - proxy_default

networks:
  proxy_default:
    external: true

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
